name: Bug Report
description: File a bug report
title: "[Bug]"
labels: Bug
assignees: HDVinnie
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        The more detailed this bug report is, the faster it can be reviewed and fixed.
  - type: input
    id: version-unit3d
    attributes:
      label: UNIT3D Version
      description: UNIT3D version your using?
      placeholder: 6.0.3
    validations:
      required: true
  - type: input
    id: version-php-os
    attributes:
      label: PHP & Platform
      description: Exact PHP and Platform (OS) versions your using.
      placeholder: 8.1.2 - Ubuntu 22.04 x64
    validations:
      required: true
  - type: input
    id: version-laravel
    attributes:
      label: Laravel verion
      description: Exact Laravel version using this package.
      placeholder: 9.2.3
    validations:
      required: true
  - type: checkboxes
    id: requeriments
    attributes:
      label: Have you done this?
      options:
        - label: I am willing to share my stack trace and logs
          required: true
        - label: I can suggest a fix as a Pull Request
          required: false
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: Write what you expect to (correctly) happen.
      placeholder: When I do this, I expect to this to happen.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write what (incorrectly) happens instead.
      placeholder: Instead, when I do this, I receive that.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Stack trace & logs
      description: If you have a stack trace, you can copy it here. You may hide sensible information.
      placeholder: This is automatically formatted into code, no need for backticks.
      render: shell
    validations:
      required: false
  - type: dropdown
    id: supporter
    attributes:
      label: Are you a UNIT3D sponsor?
      description: GitHub sponsors get priority review, fixing and responses. Are you not? [Become one!](https://github.com/sponsors/HDVinnie)
      options:
        - Yes, with my username
        - No, don't give priority to this
    validations:
      required: true
